### ISSUE TITLE
Error installing mjpeg-consumer

### ISSUE THREAD

**Issue by CedszxcJulian** [mmaelzer/mjpeg-consumer#17]
Hi, Good day. 

I`m installing the mjpeg-consumer npm module, but im stuck in this error, can you help me solve this one? Thank you very much. 

`C:\Users\MGRicafranca\aws-motion-detection\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\MGRicafranca\aws-motion-detection\node_modules\buffertools
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN aws-motion-detection@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buffertools@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@2.1.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MGRicafranca\AppData\Roaming\npm-cache\_logs\2018-08-06T01_14_51_480Z-debug.log
`

Regards,
Ced

**Comment by mmaelzer** [comment]
From your pasted error, it appears that you need to install Python: `gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`

https://www.python.org/download/releases/2.7/

**Comment by CedszxcJulian** [comment]
Thank you sir.
