### ISSUE TITLE
dependencies  'buffertools' no longer maintained and doesn't work with newer versions of Node.js

### ISSUE THREAD

**Issue by eyison** [mmaelzer/mjpeg-consumer#18]
my issue detail you can visit
[https://github.com/bnoordhuis/node-buffertools/issues/96](https://github.com/bnoordhuis/node-buffertools/issues/96)

The author says
> this module is no longer maintained and doesn't work with newer versions of Node.js.
> Most functionality is now available through the native Buffer class.**

**Comment by mmaelzer** [comment]
Fixed in https://github.com/mmaelzer/mjpeg-consumer/commit/1b90108aed70a8e90def2124b77d4662898f5401.

Install v2.0.0 of mjpeg-consumer.
